name: template
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  autoequal: ^0.7.1
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  rive: ^0.12.4
  supabase_flutter: ^2.0.2
  json_annotation: ^4.8.1
  sliver_tools: ^0.2.12
  photo_view: ^0.14.0
  url_launcher: ^6.3.1
  table_calendar: ^3.0.9
  intl: ^0.19.0
  chips_choice: ^3.0.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

dev_dependencies:
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  autoequal_gen: ^0.7.1
  bloc_test: ^9.1.6
  build_runner: ^2.4.7
  copy_with_extension_gen: ^5.0.4
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.5.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Semibold.ttf
          weight: 600
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
